### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_font_conv#7]
Current convertor implements "reader" and "dumper". Now users can focus on creating "writers", without learning vector fonts details.

To make things useable (with new features), it worth to implement this steps:

- [x] Create new font specification
- [x] Investigate compressions (need binary writer)
- [x] Create writer for LVGL 6.0

---
Note, i'm interested only to investigate compressions. As a side effect - create font spec.

**Comment by kisvegabor** [comment]
> Note, i'm interested only to investigate compressions. As a side effect - create font spec.

Without the v6.0 writer, we can use the new fonts in LittlevGL v6.0. So this writer is very important because the converter's result already won't be compatible with 5.x but without the 6.0 writer, we can't update LittlevGL. In other words, the converter won't be compatible with anything.

@puzrin I don't want to push you to do what you don't want but as you can see this writer is very important and without it the converter can't be used. Is it possible to change your mind and add the writer? If not we have two options:
1. We need to find someone who would like to be involved in this project and add the writer (very soon, before releasing v6.0)
2. Leave the fonts and the font converter as it is.

**Comment by puzrin** [comment]
I started convertor as:

- "modern CLI replacement" for lvgl5 format.
- sandbox for compressions.

But in process of rasterizer implementation, requirements changed significantly. Now i can promiss only 2 things:

- Code is modular and does not lock parallel work.
- I continue do mandadory steps - spec write & compression experiments. And this is not step back or aside.

That's still movement forward.

**Comment by puzrin** [comment]
To clarify details. I don't like idea to write fonts as C code, but this should not block us from moving forward. Also, that approach was for "old" font formats, and you may not know total data complexity for new one. May be, after spec discussion you change your opinion.

First, since we all have time constrains, we should have clear goals to reach. My personal goal is **Having MD interface on 16K RAM 128K Flash stm32**. If this can be reached - i'm motivated somehow. If not - sorry :). That includes:

- Good font rendering quality ("floating" bitmaps of any size + kerning).
- Compression (because 16-32px fonts may not fit into 128K, even restricted to ASCII only).
- Settings menu demo
- Demos with PlatformIO.

Now, let's narrow things to font issues only.

---

Architecture design prosess usually looks like this:

1. Design data formats (~ data flow)
2. Analyze problems and limitations
3. Loop to (1) until not satisfied.

Then, the same for code:

1. Try to make (or imagine) implementation. Usually, API designed on this phase.
2. Analyze problems.
3. If not satisfied - return to data design and repeat iterations.

Example: after attempt to load font data, we found existing (lvgl5) fonts completely not suitable for "good output". That was first iteration.

Then, i started to write spec, and tried to make things similar to old principles. After some time i found that complexity slowly drifts to nightmare. So, decided to rearrange things more close to OpenType principles. That was second iteration.

Also note, OpenType structure probably eliminated need of "sparse format" (not ideal design decision). In worst case - this will be condensed in small fraction of data (subtable). Any table can now be changed independently, without risk to touch everything.

Now we are on third iteration - need to rework internal font API in C (if no more format bugs found). In parallel - i should experiment with compression.

And only on the last step we can discuss some beautification about C-style font dumper. From my personal point of view, this can (and should) be avoided with ease. But anyway, that's only the final step, doable by "anyone motivated".

---

As you see, all process consists of self-sufficient steps, and nothing is "critically blocked" by my preferences. Also, everything can be "frozen" anytime and continued by anyone else. All previous results, at any point, remains valuable and nothing will be lost.

**Comment by kisvegabor** [comment]
Thanks for the clarification. I also would like to clarify my goals/vision regarding LittlevGL:
1. The most important thing is to keep it easy to use and understandable even for novice users. That's why I was against the use of Makefiles (or others) by default. 
2. The library needs to be kept light weighted even at the cost of quality. E.g. the current implementation of drawing algorithms doesn't have world-class quality but don't use significant RAM or CPU and still support nice features (e.g. anti-aliasing) which are not common in embedded GUI libraries (especially free and open source ones). That's why we can't introduce float numbers and methods which require large buffers. In other words, LittlevGL doesn't have to be better than desktop GUI libraries. We need to respect some limitations due to the embedded nature of the library. However, I agree that we need to make the API as flexible as possible, e.g. to attach FreeType and the make the most out of it. 
3. A complete rework of the font system would be too much for v6.0. So we need to make some compromise  here. Which would be a step ahead to update the fonts to support bounding box model and make possible to add kerning support later without breaking the API. With this we alredy start to use your converter. 
4. You mentioned that you are interested in implementing the lvgl5 writer. However, v5.0 will be outdated in 2 months. Creating lvgl6 writer instead seem the same amount of work and has more sens.

**Comment by puzrin** [comment]
>     1. The most important thing is to keep it easy to use and understandable even for novice users. That's why I was against the use of Makefiles (or others) by default.

Let's keep things separate. "Makefile" worth to include ONLY to regenerate built-in fonts, for consistency (to have proven source). User will not use it => will not be affected.
 
>     2. The library needs to be kept light weighted even at the cost of quality. E.g. the current implementation of drawing algorithms doesn't have world-class quality but don't use significant RAM or CPU and still support nice features (e.g. anti-aliasing) which are not common in embedded GUI libraries (especially free and open source ones). That's why we can't introduce float numbers and methods which require large buffers. In other words, LittlevGL doesn't have to be better than desktop GUI libraries. We need to respect some limitations due to the embedded nature of the library. However, I agree that we need to make the API as flexible as possible, e.g. to attach FreeType and the make the most out of it.

I completely agree, LVGL should be properly targeted. Because if hardware is powerful, it's more reasonable to use linux + full featured GUI-s like QT and so on.

My point is, that restricted features does not mean "ugly interface". With my preliminary estimates, settings menu in "material" style can be done with LVGL. And as you see, i don't say "you should make things better", but actively participate to make this dream more close to reality.

>     3. A complete rework of the font system would be too much for v6.0. So we need to make some compromise  here. Which would be a step ahead to update the fonts to support bounding box model and make possible to add kerning support later without breaking the API. With this we already start to use your converter.

Things are not so difficult. I just mean "dont't try to fit required features in existing API". Go from data, not from code. It's more simple to redesign API from scratch (and then copy-paste most of code). As architect i can say, API rework is more simple than font data design.

May be, in the end, we will get we will get the same API. But it will be powered by data, instead of blind fitting to current limitations. 

API design != coding. That's just writing signatures, and checking input/output data are consistent and convenient. Nothing special.

>     4. You mentioned that you are interested in implementing the lvgl5 writer. However, v5.0 will be outdated in 2 months. Creating lvgl6 writer instead seem the same amount of work and has more sens.

Let's split it to parts:

1. I was ready to make v5.0 text writer, because data was very simple. That's still true.
2. After investigations, and diving into details, data was changed significantly. v6.0 data (proposed in spec) is NOT so simple. Having text writer will duplicate work & add pain for sync bin & text writes.

IMHO this is case, when approaches, been good for simple data, are not guaranteed to scale up for complex data and "true distributed development". However, probably i don't understand something in this programming world :)

Anyway, i think, we will solve this somehow. My suggestion is to be consecutive, and not try to jump over middle steps to the end. Now it's time to make iteration for data verify and API design. IMHO this can be done in several days.

I can participate with API verification and corrections, but need someone to make first step with skeleton and answer my stupid questions about C and LVGL requirements. Also, i'm ready to write new API requirements (about not supported features).

**Comment by kisvegabor** [comment]
I agree in general. I was thinking about why I wasn't so welcoming with the new features and realized that my "hidden problem" was that I thought the font converter will be "just" rewritten in a compatible way to replace the current PHP converter. Therefore I tried to get an at least almost compatible converter. 

It's also fine to completely rework it. In fact, the proposed features are great and will add a lot of value to LittlevGL but it needs a different mindset from my side. So sorry if I didn't respect your work and efforts.

I will continue with this in mind and be more open to for a new API and features!

**Comment by puzrin** [comment]
> I thought the font converter will be "just" rewritten in a compatible way to replace the current PHP converter

It was really started like this. But, after we implemented some mandatory (from my point of view) quality requirements, i found simple rewrite is not enougth.

- We cared about exact font rendering. Now glyphs have right size (the same as you set in browser)
- Hinting was used to make images more sharp (free bonus)
- We "invented" concept of "floating bitmap positioning" to properly show "overflows"
  - Important: now `advanceWidth` is NOT related to bitmap, consider it as "cursor shift after glyph display"
- We found how to extract kerning
- We did dumper to quickly experiment with quality and assumptions.

All this may not be evident, when you see dumped images, but that's a huge difference with existing convertor.

If select minimal set of features, to make fonts change consistent, i see this:

- kerning
- floating bitmaps (not enougth for good look without kerning)

Optional features are:

- compression (i hope this can be done to 6.0 deadline, but data and API refine are much more important)

**Comment by kisvegabor** [comment]
Okay, let's continue in the [API topic](https://github.com/littlevgl/lvgl/issues/1006).

**Comment by puzrin** [comment]
Closing - no more package-specific questions to discuss. Everything else can be discussed in new issues or in LVGL tracker.
